services:
  db:
    image: postgres:16
    container_name: tfg-postgres
    restart: always
    environment:
      POSTGRES_USER: raul
      POSTGRES_PASSWORD: raul123
      POSTGRES_DB: tfg_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
